import { texte } from '@/lib/i18n/texte';

/* Dokumente, Projekte und das Löschen — Seiten, Formulare und Rückmeldungen. */
export const DOKUMENTE = texte({
  de: {
    metaTitel: 'Dokumente – Evidarium',
    titel: 'Dokumente',
    anzahl: (n: number) => (n === 1 ? '1 Dokument' : `${n} Dokumente`),
    hinzufuegen: 'Dokument hinzufügen',
    keine: 'Noch keine Dokumente. Lade ein PDF, eine Textdatei oder Markdown hoch.',
    grenzen: (mib: number, seiten: number) =>
      `PDF mit Textschicht, TXT oder Markdown. Höchstens ${mib} MiB und ${seiten} Seiten.`,
    seiten: (n: number) => `${n} Seiten`,
    abschnitte: (n: number) => `${n} Abschnitte`,
    zeichen: (n: string) => `${n} Zeichen`,
    projekte: {
      titel: 'Projekte',
      erklaerung:
        'Gruppen von Dokumenten. Beim Fragen lässt sich die Suche auf ein Projekt eingrenzen.',
      neu: 'Neues Projekt',
      anlegen: 'Anlegen',
      bearbeiten: 'Bearbeiten',
      bearbeitenName: (name: string) => `Bearbeiten: ${name}`,
      neuerName: 'Neuer Name',
      speichern: 'Speichern',
      loeschenFrage: 'Projekt löschen …',
      loeschenWarnung:
        'wird gelöscht. Die Dokumente darin bleiben und stehen danach ohne Projekt da.',
      loeschen: 'Projekt löschen',
      loescht: 'Wird gelöscht …',
      abbrechen: 'Abbrechen',
      ohneProjekt: 'Ohne Projekt',
      projektFuer: (datei: string) => `Projekt für ${datei}`,
      einheit: (n: number) => (n === 1 ? 'Dokument' : 'Dokumente'),
    },
    detail: {
      zurueck: 'Dokumente',
      parser: (parser: string, zerleger: string) =>
        `Gelesen mit Parser ${parser}, zerlegt mit ${zerleger}.`,
      gelesen: 'Gelesener Text',
      seite: (n: number) => `Seite ${n}`,
      abschnitt: 'Abschnitt',
      zeile: (n: number) => `Zeile ${n}`,
      zeilen: (von: number, bis: number) => `Zeilen ${von}–${bis}`,
    },
    loeschen: {
      knopf: 'Dokument löschen',
      warnung:
        'wird mit allen Abschnitten und Vektoren entfernt. Die Datei wird vom Datenträger gelöscht. Das lässt sich nicht rückgängig machen.',
      endgueltig: 'Endgültig löschen',
      loescht: 'Wird gelöscht …',
      abbrechen: 'Abbrechen',
    },
    meldung: {
      abgelehnt: 'Anfrage abgelehnt.',
      unbekannt: 'Unbekanntes Dokument.',
      gibtEsNicht: 'Dieses Dokument gibt es nicht.',
      leer: 'Gib dem Projekt einen Namen.',
      zuLang: (n: number) => `Höchstens ${n} Zeichen.`,
      gibtEsSchon: 'Ein Projekt mit diesem Namen gibt es schon.',
      zuViele: (n: number) => `Mehr als ${n} Projekte sind nicht vorgesehen.`,
      nichtGefunden: 'Dieses Projekt oder Dokument gibt es nicht.',
      angelegt: 'Projekt angelegt.',
      umbenannt: 'Umbenannt.',
      geloescht: 'Projekt gelöscht, die Dokumente sind noch da.',
      zugeordnet: 'Zugeordnet.',
    },
  },
  fr: {
    metaTitel: 'Documents – Evidarium',
    titel: 'Documents',
    anzahl: (n: number) => (n === 1 ? '1 document' : `${n} documents`),
    hinzufuegen: 'Ajouter un document',
    keine: 'Aucun document pour l’instant. Téléversez un PDF, un fichier texte ou du Markdown.',
    grenzen: (mib: number, seiten: number) =>
      `PDF avec couche de texte, TXT ou Markdown. Au plus ${mib}\u00a0Mio et ${seiten} pages.`,
    seiten: (n: number) => `${n} pages`,
    abschnitte: (n: number) => `${n} passages`,
    zeichen: (n: string) => `${n} caractères`,
    projekte: {
      titel: 'Projets',
      erklaerung:
        'Des groupes de documents. Lors des questions, la recherche peut être limitée à un projet.',
      neu: 'Nouveau projet',
      anlegen: 'Créer',
      bearbeiten: 'Modifier',
      bearbeitenName: (name: string) => `Modifier\u00a0: ${name}`,
      neuerName: 'Nouveau nom',
      speichern: 'Enregistrer',
      loeschenFrage: 'Supprimer le projet …',
      loeschenWarnung:
        'sera supprimé. Les documents qu’il contient restent et n’appartiennent ensuite à aucun projet.',
      loeschen: 'Supprimer le projet',
      loescht: 'Suppression …',
      abbrechen: 'Annuler',
      ohneProjekt: 'Sans projet',
      projektFuer: (datei: string) => `Projet pour ${datei}`,
      einheit: (n: number) => (n === 1 ? 'document' : 'documents'),
    },
    detail: {
      zurueck: 'Documents',
      parser: (parser: string, zerleger: string) =>
        `Lu avec le parseur ${parser}, découpé avec ${zerleger}.`,
      gelesen: 'Texte lu',
      seite: (n: number) => `Page ${n}`,
      abschnitt: 'Passage',
      zeile: (n: number) => `Ligne ${n}`,
      zeilen: (von: number, bis: number) => `Lignes ${von}–${bis}`,
    },
    loeschen: {
      knopf: 'Supprimer le document',
      warnung:
        'sera retiré avec tous ses passages et vecteurs. Le fichier sera effacé du support. Cette action est irréversible.',
      endgueltig: 'Supprimer définitivement',
      loescht: 'Suppression …',
      abbrechen: 'Annuler',
    },
    meldung: {
      abgelehnt: 'Requête refusée.',
      unbekannt: 'Document inconnu.',
      gibtEsNicht: 'Ce document n’existe pas.',
      leer: 'Donnez un nom au projet.',
      zuLang: (n: number) => `${n} caractères au plus.`,
      gibtEsSchon: 'Un projet portant ce nom existe déjà.',
      zuViele: (n: number) => `Plus de ${n} projets ne sont pas prévus.`,
      nichtGefunden: 'Ce projet ou ce document n’existe pas.',
      angelegt: 'Projet créé.',
      umbenannt: 'Renommé.',
      geloescht: 'Projet supprimé, les documents sont toujours là.',
      zugeordnet: 'Attribué.',
    },
  },
  it: {
    metaTitel: 'Documenti – Evidarium',
    titel: 'Documenti',
    anzahl: (n: number) => (n === 1 ? '1 documento' : `${n} documenti`),
    hinzufuegen: 'Aggiungi documento',
    keine: 'Ancora nessun documento. Carichi un PDF, un file di testo o Markdown.',
    grenzen: (mib: number, seiten: number) =>
      `PDF con livello di testo, TXT o Markdown. Al massimo ${mib} MiB e ${seiten} pagine.`,
    seiten: (n: number) => `${n} pagine`,
    abschnitte: (n: number) => `${n} passaggi`,
    zeichen: (n: string) => `${n} caratteri`,
    projekte: {
      titel: 'Progetti',
      erklaerung: 'Gruppi di documenti. Nelle domande la ricerca si può limitare a un progetto.',
      neu: 'Nuovo progetto',
      anlegen: 'Crea',
      bearbeiten: 'Modifica',
      bearbeitenName: (name: string) => `Modifica: ${name}`,
      neuerName: 'Nuovo nome',
      speichern: 'Salva',
      loeschenFrage: 'Elimina progetto …',
      loeschenWarnung:
        'viene eliminato. I documenti che contiene restano e in seguito non appartengono ad alcun progetto.',
      loeschen: 'Elimina progetto',
      loescht: 'Eliminazione …',
      abbrechen: 'Annulla',
      ohneProjekt: 'Senza progetto',
      projektFuer: (datei: string) => `Progetto per ${datei}`,
      einheit: (n: number) => (n === 1 ? 'documento' : 'documenti'),
    },
    detail: {
      zurueck: 'Documenti',
      parser: (parser: string, zerleger: string) =>
        `Letto con il parser ${parser}, suddiviso con ${zerleger}.`,
      gelesen: 'Testo letto',
      seite: (n: number) => `Pagina ${n}`,
      abschnitt: 'Passaggio',
      zeile: (n: number) => `Riga ${n}`,
      zeilen: (von: number, bis: number) => `Righe ${von}–${bis}`,
    },
    loeschen: {
      knopf: 'Elimina documento',
      warnung:
        'viene rimosso con tutti i passaggi e i vettori. Il file viene cancellato dal supporto. Non è possibile annullare.',
      endgueltig: 'Elimina definitivamente',
      loescht: 'Eliminazione …',
      abbrechen: 'Annulla',
    },
    meldung: {
      abgelehnt: 'Richiesta respinta.',
      unbekannt: 'Documento sconosciuto.',
      gibtEsNicht: 'Questo documento non esiste.',
      leer: 'Dia un nome al progetto.',
      zuLang: (n: number) => `Al massimo ${n} caratteri.`,
      gibtEsSchon: 'Esiste già un progetto con questo nome.',
      zuViele: (n: number) => `Non sono previsti più di ${n} progetti.`,
      nichtGefunden: 'Questo progetto o documento non esiste.',
      angelegt: 'Progetto creato.',
      umbenannt: 'Rinominato.',
      geloescht: 'Progetto eliminato, i documenti ci sono ancora.',
      zugeordnet: 'Assegnato.',
    },
  },
  en: {
    metaTitel: 'Documents – Evidarium',
    titel: 'Documents',
    anzahl: (n: number) => (n === 1 ? '1 document' : `${n} documents`),
    hinzufuegen: 'Add a document',
    keine: 'No documents yet. Upload a PDF, a text file or Markdown.',
    grenzen: (mib: number, seiten: number) =>
      `PDF with a text layer, TXT or Markdown. At most ${mib} MiB and ${seiten} pages.`,
    seiten: (n: number) => `${n} pages`,
    abschnitte: (n: number) => `${n} passages`,
    zeichen: (n: string) => `${n} characters`,
    projekte: {
      titel: 'Projects',
      erklaerung: 'Groups of documents. When asking, the search can be narrowed to one project.',
      neu: 'New project',
      anlegen: 'Create',
      bearbeiten: 'Edit',
      bearbeitenName: (name: string) => `Edit: ${name}`,
      neuerName: 'New name',
      speichern: 'Save',
      loeschenFrage: 'Delete project …',
      loeschenWarnung:
        'will be deleted. The documents in it stay and afterwards belong to no project.',
      loeschen: 'Delete project',
      loescht: 'Deleting …',
      abbrechen: 'Cancel',
      ohneProjekt: 'No project',
      projektFuer: (datei: string) => `Project for ${datei}`,
      einheit: (n: number) => (n === 1 ? 'document' : 'documents'),
    },
    detail: {
      zurueck: 'Documents',
      parser: (parser: string, zerleger: string) =>
        `Read with parser ${parser}, split with ${zerleger}.`,
      gelesen: 'Text as read',
      seite: (n: number) => `Page ${n}`,
      abschnitt: 'Passage',
      zeile: (n: number) => `Line ${n}`,
      zeilen: (von: number, bis: number) => `Lines ${von}–${bis}`,
    },
    loeschen: {
      knopf: 'Delete document',
      warnung:
        'will be removed with all its passages and vectors. The file is erased from disk. This cannot be undone.',
      endgueltig: 'Delete for good',
      loescht: 'Deleting …',
      abbrechen: 'Cancel',
    },
    meldung: {
      abgelehnt: 'Request rejected.',
      unbekannt: 'Unknown document.',
      gibtEsNicht: 'This document does not exist.',
      leer: 'Give the project a name.',
      zuLang: (n: number) => `At most ${n} characters.`,
      gibtEsSchon: 'A project with this name already exists.',
      zuViele: (n: number) => `More than ${n} projects are not supported.`,
      nichtGefunden: 'This project or document does not exist.',
      angelegt: 'Project created.',
      umbenannt: 'Renamed.',
      geloescht: 'Project deleted; the documents are still there.',
      zugeordnet: 'Assigned.',
    },
  },
});
